namespace SavLibrary {
    public enum ArmGearType {
        FaeriesRing = 43,
        ElbowPad,
        PowerVambrace,
        CobraBracelet,
        WolfsBand,
        SilverBand,
        GolemRing,
        FrostyRing,
        IvyAmulet,
        GoldBracelet,
        ShieldRing,
        LazuliVambrace,
        GuardianRing,
        Vambrace,
        NinjaGloves,
        DragonCoil,
        WatcherRing,
        ImpsRing,
        AmuletRing,
        Wristband,
    }

    public enum BodyGearType {
        Overalls = 22,
        KungFuSuit,
        MinorRobe,
        ChainVest,
        SpikySuit,
        KungFuDress,
        FancyOveralls,
        ChestGuard,
        GoldenVest,
        RubyVest,
        TigerSuit,
        TigerTwoPiece,
        MagicalArmour,
        TortoiseMail,
        FlowerSuit,
        BattleSuit,
        Vestguard,
        VampireCape,
        PowerSuit,
        FaerieCloak,
    }

    public enum HeadGearType {
        Bandana = 1,
        HairRibbon,
        RabiteCap,
        HeadGear,
        QuillCap,
        SteelCap,
        GoldenTiara,
        RaccoonCap,
        QuiltedHood,
        TigerCap,
        Circlet,
        RubyArmet, // Not available in the game
        UnicornHelm,
        DragonHelm,
        DuckHelm,
        NeedleHelm,
        CockatriceCap,
        AmuletHelm,
        GriffinHelm,
        FaerieCrown,
    }

}
